### ISSUE TITLE
readme & encyclopedists using old style of author contributions

### ISSUE THREAD

**Issue by richardjtelford** [arnaudgallou/plume#26]
The example on the readme, and `plume::encyclopedists` is using the old style  of author contribution.

Is it possible to allow numbers other than 1 in the role to allow for ranking the contributions?

Is it possible to internationalise the role names (visualisation vs. visualization), and allow ad hoc contributions?

**Comment by arnaudgallou** [comment]
* The "old style" of author contribution is still in use and currently the only way to use custom roles. I kept it in most of the examples because it is a more generalised approach to define roles than the way plume handles CRediT roles.

* Do you mean a way to control the order of contributions? E.g. using `1` for `investigation` and `2` for `analysis` to have `investigation` come before `analysis`.
Or do you mean a way to control the order of authors in a given role? E.g. using `1`, `2`, `3` (etc.) for say `analysis` to rearrange author names in the contribution list.

* Currently, the only way to do that is to use the following data structure:

``` r
#> # A tibble: 2 × 5
#>   given_name family_name role_1            role_2        role_3 
#>   <chr>      <chr>       <chr>             <chr>         <chr>  
#> 1 Zip        Zap         conceptualisation NA            writing
#> 2 Ric        Rac         NA                visualisation writing
```

**Comment by richardjtelford** [comment]
I've found the issue  - plume has changed from using  "contribution" to "role" for the column headers which broke my manuscript with the error:

>Error:
! Column `role` doesn't exist.

This confused me, and I didn't realise what had changed, and when I found the new vignette, I though that was it. Maybe the vignette should show both methods.

Encyclopedists has columns role_n1 role_n2 role_v1 role_v2 - what do the n and v signify?

With regard to ordering the contribution, I was imagining something like this
``` r
library(plume)
tmp <- plm_template(credit_roles = TRUE) |> 
  dplyr::add_row(given_name = c("A", "C"), family_name = c("Jones", "Smith"), conceptualization = as.character(1:2), data_curation = as.character(2:1))

Plume$new(tmp, credit_roles = TRUE)$get_contributions()
#> Conceptualization: A.J. C.S.
#> Data curation: C.S. A.J.
```
Where AJ  lead the conceptualisation and CS lead the data curation.

Would be nice if `plm_template(credit_roles = TRUE)` had the role columns as numeric

**Comment by arnaudgallou** [comment]
* Ah yeah, I made quite some changes since the first version I showed you. I changed the default name to `role` to align with [Quarto's new YAML key `roles`](https://quarto.org/docs/authoring/front-matter.html#author) and because the name was shorter. The pkdown site already shows all the different ways to use roles. CRediT roles are specific enough that it made sense to me to put it in a separate article. Would you prefer to have it in the "Get started" page?

* One can read in `?encyclopedists`:

> **role_n**
authors' roles written as nouns
**role_v**
authors' roles written as active verbs

The `n` and `v` are the short for `noun` and `verb`, respectively. The names don't matter much, it was a way for me to include different role styles in the same data set. You can see the 2 styles in use [here](https://arnaudgallou.github.io/plume/articles/plume.html#contributions).

* I'm planning to implement a new method to set the [degree of contribution](https://quarto.org/docs/authoring/front-matter.html#roles) in a future release. See #14.
In `Plume`, the method will allow users to control the order of authors' names in any given roles.
In the meantime, if you really need to change the order of names, I'd simply generate the contribution list separately, paste it to the manuscript and make the changes manually.

* plume really is designed to work with spreadsheets to enter data (see the [plume workflow](https://arnaudgallou.github.io/plume/articles/plume-workflow.html) vignette for the recommended approach). The only benefit I see of having role columns as numeric is to make the entering of data in R easier, which is something people should avoid in the first place. I'll reconsider it but that should normally be of no use for people following the recommended workflow, while adding a bit of complexity in the code.
